### ISSUE TITLE
Research other sources for free online medical texts

### ISSUE THREAD

**Issue by tschimbr** [eonum/medtextcollector#2]
http://www.freebookcentre.net/medical_text_books_journals/medical_text_books_online.html
http://www.medicalstudent.com/
http://www.freebooks4doctors.com/
http://www.freebooks4doctors.com/f.php?f=de
http://www.freemedicaljournals.com/

**Comment by asittampalam** [comment]
http://www.msd-manual.de/msdmanual/ - Its available for free. I'm not sure if we're legally allowed to process it though.
