### ISSUE TITLE
Extract synonyms from ICD / CHOP / other sources

### ISSUE THREAD

**Issue by tschimbr** [eonum/medtextcollector#7]
in order to evaluate word vectors created by a corpus based on the correlation of word vector similarities (cosine distances) and these synonyms.

**Comment by tschimbr** [comment]
Another source could also be the synonyms as used in drg-search. (in the respective data directory). ICD / CHOP synonyms can be found in the medcodesearch DB.

**Comment by tschimbr** [comment]
Negative examples should also be included.

**Comment by asittampalam** [comment]
Is this being solved in https://github.com/eonum/medword now?

**Comment by asittampalam** [comment]
Moved to https://github.com/eonum/medword/issues/8.
